name: Bug report
description: Report a bug to help us improve
title: "[BUG] Brief description of the issue"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        **Describe the bug**
        A clear and concise description of what the bug is.

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to reproduce"
      description: "Steps to reproduce the behavior"
      placeholder: "1. Go to '...'\n2. Run '....'\n3. See error"

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen"
      placeholder: "Expected behavior"

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem"
      placeholder: "Add screenshots here"

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here"
      placeholder: "Additional context"
