name: Feature request
description: Suggest an idea for this project
title: "[FEATURE] Brief description of the feature"
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        **Is your feature request related to a problem? Please describe.**
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

  - type: textarea
    id: solution
    attributes:
      label: "Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen"
      placeholder: "Describe the solution"

  - type: textarea
    id: alternatives
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered"
      placeholder: "Describe alternatives"

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request here"
      placeholder: "Additional context"
